B2B-Ecommerce-Platform/api/urls.py
from django.urls import path

app_name = "api"

from api import views

urlpatterns = [
    path("stores/", views.StoresListView.as_view(), name="stores"),
    path(
        "supplier/contracts/",
        views.SupplierContractsListView.as_view(),
        name="supplier/contracts",
    ),
    path("services/", views.ServicesListView.as_view(), name="services"),
    path("contracts/", views.ContractsListView.as_view(), name="contracts"),


    #---------------------------------------- Products ----------------------------------------
    path("products/", views.ProductsListView.as_view(), name="products"),
    path("supplier/products/", views.SupplierProductsListView.as_view(), name="supplier-products"),
    path("supplier/products/create/", views.ProductCreateApiView.as_view(), name="supplier-product-create"),
    path("supplier/products/<str:slug>/create/<str:data_type>/", views.ProductAppendDetailsApiView.as_view(), name="supplier-product-append-details"),
    path(
        "loading_products/",
        views.LoadingProductsListView.as_view(),
        name="loading_products",
    ),
    #---------------------------------------- Products ----------------------------------------

    #---------------------------------------- Calender ----------------------------------------
    path("events/", views.CalenderEventListView.as_view(), name="events"),
    path("events/create/", views.CalenderEventCreateView.as_view(), name="event-create"),
    path("events/<int:pk>/details/", views.CalenderEventDetailView.as_view(), name="event-detail"),
    path("events/<int:pk>/delete/", views.CalenderEventDeleteView.as_view(), name="event-detail"),
    #---------------------------------------- Calender ----------------------------------------


    #---------------------------------------- Cart ----------------------------------------
    path("cart/", views.CartListView.as_view(), name="cart"),
    path("cart/product/<str:product_slug>/add/", views.CartAppeendAppendView.as_view(), name="cart-add-product"),
    path("cart/product/<str:product_slug>/delete/", views.CartDeleteProductView.as_view(), name="cart-delete-product"),
    #---------------------------------------- Cart ----------------------------------------

    #---------------------------------------- Notifications ----------------------------------------
    path("notifications/", views.NotificationListView.as_view(), name="notification-list"),
    path("notifications/business/", views.NotificationBusinessListView.as_view(), name="Notification-business-list"),
    path("notifications/<str:category>/", views.NotificationCategoryListView.as_view(), name="Notification-category-list"),
    path("notifications/<int:pk>/delete/", views.NotificationDeleteView.as_view(), name="Notification-delete"),
    # path("notifications/<int:pk>/update/", views.NotificationUpdateView.as_view(), name="Notification-update"),
    #---------------------------------------- Notifications ----------------------------------------


    #---------------------------------------- chat ----------------------------------------
    path("user/<int:pk>/", views.UserInfoView.as_view(), name="user-info-retrieve"),
    path("business/<int:pk>/", views.BusinessInfoView.as_view(), name="business-info-retrieve"),
    path("chats/", views.ChatListView.as_view(), name="chat-list"),
    #---------------------------------------- chat ----------------------------------------

    path("chats/group/create/", views.CreateGroupChat.as_view(), name="create-group"),

]

B2B-Ecommerce-Platform/coms/urls.py
from django.urls import path
from coms import views as ComsViews

app_name = "coms"


urlpatterns = [
    path("interclient/<str:business_slug>/", ComsViews.InterClientChatInitView.as_view(), name="interclient-chat-init"),
    path("groups/<str:roomname>/", ComsViews.GroupChatAppendView.as_view(), name="group-chat-append"),
]

B2B-Ecommerce-Platform/core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext as _

from manager import views
from payment.views import InitSubscriptionView

from django.core.signals import request_finished
from django.dispatch import receiver


# @receiver(request_finished)
# def my_callback(sender, **kwargs):
#     print("Request finished!")


# @receiver(request_finished)
# def requestTracker(request, **kwargs):
#     print(kwargs)
#     # if request.user_agent.is_mobile:
#     #     user_device = "mobile"
#     # elif request.user_agent.is_tablet:
#     #     user_device = "tablet"
#     # elif request.user_agent.is_bot:
#     #     user_device = "bot"
#     # else:
#     #     user_device = "pc"


#     print("*"*50)
#     print("Request finished!")
#     print("*"*50)
#     pass


# @receiver(got_request_exception)
# def get_exception_response(request, resolver, status_code, exception, sender=None):
# try:
#     callback, param_dict = resolver.resolve_error_handler(status_code)
#     response = callback(request, **dict(param_dict, exception=exception))
# except Exception:
#     signals.got_request_exception.send(sender=sender, request=request)
#     response = handle_uncaught_exception(request, resolver, sys.exc_info())

# return response
# pass


urlpatterns = i18n_patterns(
    path("", include("manager.urls", namespace="manager")),
    path(_("suppliers/"), include("supplier.urls", namespace="supplier")),
    path(_("buyer/"), include("buyer.urls", namespace="buyer")),
    path(_("auth/"), include("auth_app.urls", namespace="auth")),
    path(_("payments/"), include("payment.urls", namespace="payments")),
    path(_("support/admin/"), include("app_admin.urls", namespace="app_admin")),
    path(_("api/"), include("api.urls", namespace="api")),
    path(_("admin-api/"), include("admin_api.urls", namespace="admin-api")),
    path(_("communications/"), include("coms.urls", namespace="coms")),
    path(_("admin/"), admin.site.urls),
)
urlpatterns += [
    path("accounts/inactive/", InitSubscriptionView.as_view()),
    path("accounts/profile/", views.HomeView.as_view()),
    path("accounts/", include("allauth.urls")),
]

if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += [re_path(r"^rosetta/", include("rosetta.urls"))]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

B2B-Ecommerce-Platform/manager/urls.py
from django.urls import path

# apps
from manager import views

app_name = "manager"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    # showrooms
    path("showrooms/", views.ShowRoomListView.as_view(), name="showrooms"),
    path(
        "showroom/<str:slug>",
        views.ShowRoomDetailView.as_view(),
        name="showroom-detail",
    ),
    # services
    path("services/", views.ServiceListView.as_view(), name="services"),
    path("about/", views.AboutUsView.as_view(), name="about-us"),
    path("profile/", views.profile, name="profile"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("support/", views.SupportView.as_view(), name="support"),
    path("support/chatroom/", views.SupportChatroomView.as_view(), name="chatroom"),
    path(
        "support/discussion/<str:slug>/",
        views.SupportDiscussionView.as_view(),
        name="discussion",
    ),
    path(
        "support/discussions/",
        views.SupportDiscussionListView.as_view(),
        name="discussions",
    ),
    path(
        "support/create-discussion/",
        views.SupportCreateDiscussionView.as_view(),
        name="create-discussion",
    ),
    path("blocked", views.blockDasboardAccess, name="dashboard-blocked"),
    path("profile404", views.ProfileNotFound, name="profile-notfound"),
    # guides
    path("guides/memberships", views.memberships, name="guides-memberships"),
    path("guides/showrooms", views.showrooms, name="guides-showrooms"),
    path("guides/stores", views.stores, name="guides-stores"),
    path("guides/services", views.services, name="guides-services"),
    path("guides/products", views.products, name="guides-products"),
    path("guides/accounts", views.accounts, name="guides-accounts"),
]

B2B-Ecommerce-Platform/supplier/urls.py
from django.urls import path

# apps
from supplier import views

app_name = "supplier"

urlpatterns = [
    # supplier
    path(
        "supplier/<str:slug>",
        views.SupplierDetailView.as_view(),
        name="supplier-detail",
    ),
    path(
        "supplier/<str:slug>/contact/",
        views.SupplierContactView.as_view(),
        name="supplier-contact",
    ),
    path(
        "supplier/contract/<str:slug>/",
        views.SupplierContractView.as_view(),
        name="supplier-contract",
    ),
    # products
    path("products/", views.ProductListView.as_view(), name="products"),
    path(
        "products/<str:slug>", views.ProductDetailView.as_view(), name="product-detail"
    ),
    path("new-arivals/", views.NewArrivalView.as_view(), name="new-arivals"),
    path("superdeals/", views.SuperDealsView.as_view(), name="superdeals"),
    # categories
    path("categories/", views.CategoryListView.as_view(), name="category-list"),
    path(
        "category/<str:slug>",
        views.CategoryDetailView.as_view(),
        name="category-detail",
    ),
    # subcategory
    path(
        "category/<str:category_slug>/subcategory/<str:sub_category_slug>",
        views.SubCategoryDetailView.as_view(),
        name="subcategory-detail",
    ),
    # store
    path(
        "store/<str:slug>",
        views.StoreDetailView.as_view(),
        name="store-detail",
    ),
    path(
        "stores",
        views.StoreListView.as_view(),
        name="store-list",
    ),
    # path("stores/", views.CategoryListView.as_view(), name="store-list"),
    # path(
    #     "category/<str:slug>",
    #     views.CategoryDetailView.as_view(),
    #     name="category-detail",
    # ),
    path(
        "search",
        views.SearchView.as_view(),
        name="search",
    ),
    # dashboard
    path("dashboard", views.DashboardView.as_view(), name="dashboard"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("business/profile/", views.BusinessProfileView.as_view(), name="business_profile"),
    path("password-reset", views.password_reset, name="password-reset"),
    path(
        "editaccountsprofile/",
        views.EditAccountsProfileView.as_view(),
        name="dashboard-editaccountsprofile",
    ),
    path(
        "editbusinessprofile/<str:slug>/",
        views.EditBusinessProfileView.as_view(),
        name="dashboard-editbusinessprofile",
    ),
    path(
        "dashboard/products",
        views.DashboardProductsView.as_view(),
        name="dashboard-products",
    ),
    path(
        "dashboard/productscreate",
        views.DashboardProductsCreateView.as_view(),
        name="dashboard-productscreate",
    ),
    path(
        "dashboard/product/<str:slug>/edit/",
        views.DashboardProductEditView.as_view(),
        name="dashboard-productedit",
    ),
    path(
        "dashboard/product/customize/<str:slug>/",
        views.DashboardProductCustomizationView.as_view(),
        name="dashboard-productscustomize",
    ),
    path(
        "dashboard/bulkupload",
        views.DashboardBulkUploadView.as_view(),
        name="dashboard-bulkupload",
    ),
    path(
        "dashboard/product/<str:slug>/delete/",
        views.DashboardProductDeleteView.as_view(),
        name="dashboard-productdelete",
    ),
    path("dashboard/product/<str:product_slug>/store/<str:slug>/delete/", views.DashboardProductStoreDeleteView.as_view(), name="dashboard-storedelete"),
    path("dashboard/product/<str:product_slug>/category/<str:slug>/delete/", views.DashboardProductCategoryDeleteView.as_view(), name="dashboard-categorydelete"),
    path("dashboard/product/<str:product_slug>/sub_category/<str:slug>/delete/", views.DashboardProductSubCategoryDeleteView.as_view(), name="dashboard-sub_categorydelete"),
    path("dashboard/product/<str:product_slug>/pricing/<int:pk>/delete/", views.DashboardProductPricingDeleteView.as_view(), name="dashboard-pricingdelete"),
    path("dashboard/product/<str:product_slug>/tag/<int:pk>/delete/", views.DashboardProductTagDeleteView.as_view(), name="dashboard-tagdelete"),
    path("dashboard/product/<str:product_slug>/color/<int:pk>/delete/", views.DashboardProductColorDeleteView.as_view(), name="dashboard-colordelete"),
    path("dashboard/product/<str:product_slug>/material/<int:pk>/delete/", views.DashboardProductMaterialDeleteView.as_view(), name="dashboard-materialdelete"),
    path("dashboard/product/<str:product_slug>/image/<str:slug>/delete/", views.DashboardProductImageDeleteView.as_view(), name="dashboard-imagedelete"),
    path("dashboard/product/<str:product_slug>/video/<str:slug>/delete/", views.DashboardProductVideoDeleteView.as_view(), name="dashboard-videodelete"),


    path(
        "dashboard/stores/",
        views.DashboardStoresView.as_view(),
        name="dashboard-stores",
    ),
    path(
        "dashboard/stores/<str:slug>/assign-showroom/",
        views.assign_showroom,
        name="dashboard-assign-showroom",
    ),
    path(
        "dashboard/stores/<str:slug>/add-product/",
        views.add_product,
        name="dashboard-add-product",
    ),
    path(
        "dashboard/storescreate",
        views.DashboardStoresCreateView.as_view(),
        name="dashboard-storescreate",
    ),
    path(
        "dashboard/contracts",
        views.DashboardContractsView.as_view(),
        name="dashboard-contracts",
    ),
    path(
        "dashboard/contractsdetails/<int:pk>",
        views.DashboardContractsDetailsView.as_view(),
        name="dashboard-contractsdetails",
    ),
    path(
        "dashboard/contract/reject/<int:pk>",
        views.DashboardContractRejectDetailsView.as_view(),
        name="dashboard-contract-reject",
    ),
    path(
        "dashboard/contract/accept/<int:pk>",
        views.DashboardContractAcceptDetailsView.as_view(),
        name="dashboard-contract-accept",
    ),
    path(
        "dashboard/messenger",
        views.DashboardMessengerView.as_view(),
        name="dashboard-messenger",
    ),
    path(
        "dashboard/notification",
        views.DashboardNotificationView.as_view(),
        name="dashboard-notification",
    ),
    path(
        "dashboard/calendar",
        views.DashboardCalendarView.as_view(),
        name="dashboard-calendar",
    ),
    path(
        "dashboard/services",
        views.DashboardServicesView.as_view(),
        name="dashboard-services",
    ),
    path(
        "dashboard/servicescreate",
        views.DashboardServicesCreateView.as_view(),
        name="dashboard-servicescreate",
    ),

    path(
        "dashboard/advertise",
        views.DashboardAdvertiseView.as_view(),
        name="dashboard-advertise",
    ),
    path(
        "dashboard/advertise/payment/<str:slug>",
        views.DashboardAdvertisePaymentView.as_view(),
        name="dashboard-advertise-payment",
    ),
    path(
        "dashboard/payments",
        views.DashboardPaymentsView.as_view(),
        name="dashboard-payments",
    ),
    path(
        "dashboard/payments/advert",
        views.DashboardAdvertsPaymentsView.as_view(),
        name="dashboard-advert-payments",
    ),

    # orders
    path(
        "dashboard/orders/",
        views.DashboardOrderList.as_view(),
        name="dashboard-order-list",
    ),
    path(
        "dashboard/orders/<str:order_id>",
        views.DashboardOrderDetail.as_view(),
        name="dashboard-order-details",
    ),
    path('dashboard/order-excel/<str:order_id>', views.download_excel, name='order_excel'),

]

B2B-Ecommerce-Platform/templates/supplier/productcategory_list.html
{% extends '../utils/layout.html' %}
{% load static %}
{% load i18n %}
{% block content %}

    <!-- <main class="grid gap-8" style="min-block-size:70vh;background-color: white;"> -->
      
        <section style="background-color: white;" class="main w-12/12 py-6">
            <div class="grid w-full mx-auto cf-1 gap-6">
                <div class="section-heading">
                    <h2 class="sec-title text-2xl font-bold">Product Categories</h2>
                </div>
                <div class="section-body grid gap-2 md:gap-4 md:grid-cols-6" data-context-name="{{context_name}}">
                    {% for category_group in object_list %}
                        <div class="grid gap-2 align-start p-2 px-4 border border-solid border-slate-200 rounded" style="align-items: flex-start;align-content: flex-start;" data-category-index="{{ forloop.counter }}">
                            <a href='{% url "supplier:category-detail" category_group.category.slug %}' class="text-base font-semibold">{{ category_group.category.name }}</a>
                            <ul class="grid gap-1 list-inside">

                                {% for sub_category in category_group.sub_categories %}
                                    <li>
                                        <a href='{% url "supplier:subcategory-detail" category_group.category.slug sub_category.slug %}' class="text-sm text-slate-700" data-subcategory-index="{{ forloop.counter }}">{{sub_category.name}}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {%endfor %}
                </div>
            </div>
        </section>

    <!-- </main> -->

{% endblock %}

B2B-Ecommerce-Platform/templates/supplier/supplier_detail.html
{% extends '../utils/layout.html' %}
{% load static %}
{% load i18n %}
{% block content %}

    <section class="main w-12/12 py-6 pt-0" style="block-size: auto;">
        <div class="breadcrumb flex flex-wrap justify-start gap-2 w-full md:w-full mx-auto px-5 pt-0">
            <a class="text-gray-600 hover:text-gray-900" href="{% url 'manager:home' %}">{% trans 'Home' %}</a>
            <a>/</a>
            <a class="text-gray-600 hover:text-gray-900" href=''>{% trans 'Suppliers' %}</a>
            <a>/</a>
            <span class="text-lightBackgroundColor capitalize">{{object.business_name}}</span>
        </div>
        <div class="grid gap-6 md:gap-10 p-5 py-0 supplier-detail w-full md:w-full mx-auto">
            <div class="grid gap-4 justify-start content-start">
                <div class="grid md:grid-flow-col justify-between gap-1">                        
                    <h3 class="text-xl md:text-2xl font-bold text-lghterBackgroundColor">
                        {{object.business_name}}</h3>
                </div>
                <div class="client-infor grid gap-6 py-4 justify-items-start" style="border-bottom: 1px solid hsla(213, 28%, 19%, .1);border-top: 1px solid hsla(213, 28%, 19%, .1)">
                    <div class="grid gap-2">
                        <h4 class="text-lg font-semibold text-lightBackgroundColor">{% trans 'About Supplier' %}</h4>
                        <p class="text-base font-normal text-slate-800">
                            {{object.business_description}}
                        </p>
                    </div>
                    <div class="grid items-start gap-2">
                        <h4 class="text-lg font-semibold">{% trans 'Detailed Supplier Information' %}</h4>
                        <span class="flex gap-1 items-start">
                            <h3 class="text-base font-semibold text-lightBackgroundColor">{% trans 'Business Name' %}: </h3>
                            <p class="font-normal text-slate-700">{{object.business_name}}</p>
                        </span>
                        <span class="grid gap-1 md:grid-flow-col gap-2">
                            <h3 class="text-base font-semibold text-lightBackgroundColor">{% trans 'Business Address' %}:</h3>
                            <ul class="list-none grid gap-1 list-inside mc:ml-0 font-normal text-slate-700">
                                <li><span class="text-slate-500">VAT No:</span> {{object.vat_number}}</li>
                                <li><span class="text-slate-500">LEI:</span> {{object.legal_etity_identifier}}</li>
                                <li>+({{object.country_code}}) {{object.mobile_user}}</li>
                                <li>{{object.city}}</li>
                                <li>{{object.country}}</li>
                                <li>{{object.website}}</li>
                            </ul>
                        </span>
                    </div>
                </div>
                <!-- <div class="grid gap-4 justify-start">
                    <div class="membership-sticker grid place-items-center text-white font-semibold px-4 py-2 " style="background-color: rgb(92, 204, 241);">Premium Supplier</div>
                    <p class="text-slate-700 flex gap-2" data-context="{{product_supplier.context_name}}">
                        <span>Country: </span>
                        <span class="font-semibold">France</span>
                    </p>
                </div> -->
                {% if request.user.business != object %}
                <div class="cta flex flex-wrap gap-3 my-3">
                    <a href="{% url 'supplier:supplier-contact' object.slug %}" class="flex place-items-center gap-3 px-5 md:px-7 py-2 text-base md:py-3 bg-yellowColor hover:bg-yellowColorHover duration-200 transition-all ease-in rounded-full text-white font-semibold">
                        <span class="text-white"><i class="fa fa-envelope"></i></span>
                        <span>{% trans 'Compose Email' %}</span>
                    </a>
                    <a href="{% url 'coms:interclient-chat-init' object.slug %}" class="flex place-items-center gap-3 px-5 md:px-7 py-2 text-base md:py-3 bg-lighterBackgroundColorHover hover:bg-lghterBackgroundColor duration-200 transition-all ease-in rounded-full text-white font-semibold">
                        <span class="text-white"><i class="fa fa-comment"></i></span>
                        <span>{% trans 'Live Chat' %}</span>
                    </a>
                    <a href="{% url 'supplier:supplier-contact' object.slug %}" class="flex place-items-center gap-3 px-5 md:px-7 py-2 text-base md:py-3 bg-black hover:bg-black duration-200 transition-all ease-in rounded-full text-white font-semibold">
                        <span class="text-white"><i class="fa fa-phone"></i></span>
                        <span>{% trans 'Schedule A Call' %}</span>
                    </a>
                </div>
                {% endif %}
            </div>
        </div>
    </section>

    {% if supplier_service.results %}
        <section class="main w-12/12 py-6 md:py-10" style="background-color: #FFFFFF;">
            <div class="grid w-full mx-auto cf-1 gap-4 md:gap-6 w-full md:w-full mx-auto">
                <div class="section-heading  flex justify-between px-4 items-center">
                    <h2 class="sec-title text-lg capitalize md:text-xl font-bold text-lghterBackgroundColor capitalize">{{object.business_name}} {% trans 'Services' %}</h2>
                </div>
                <div class="section-body grid gap-4 md:gap-3 grid-cols-1 md:grid-cols-4" data-content="{{supplier_service.context_name}}">
                    {% for service in supplier_service.results %}
                        <div class="service grid gap-3 p-4 card-outlined rounded content-start">
                            <h2 class="text-lg font-semibold text-lghterBackgroundColor">{{service.service.name}}</h2>
                            <hr/>

                            <div class="grid gap-2">
                                <p class="text-base text-slate-700 font-normal">
                                    {{service.service.description}}
                                </p>

                                <div class="flex gap-1 flex-wrap">
                                    {% for tag in service.tags %}
                                        <span style="color: hsla(189, 96%, 30%, 0.836);">{{tag.name}}, </span>
                                    {% endfor %}
                                </div>

                                <a href="{% url 'supplier:supplier-contract' service.service.slug %}" class="flex place-items-center gap-2 px-2 text-base text-yellowColor duration-200 transition-all ease-in rounded-full  font-semibold justify-self-start">
                                    <span><i class="fa fa-money"></i></span>
                                    <span>Make Contract</span>
                                </a>
                            </div>

                            {% if service.service.contract_count %}
                                <hr>
                                <p class="text-base text-slate-500 font-normal">
                                    <span class="font-semibold">
                                        {{service.service.contract_count}}</span>
                                    <span>Contracted Customers</span>
                                </p>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    {% endif %}

    {% if products.results %}
        <section class="main w-12/12" style="block-size: auto">
            <div class="grid w-full mx-auto cf-1 gap-4" style="grid-template-columns: 1fr;">             
                <div class="flex p-2 px-2 pt-0 justify-between items-baseline">
                    <div class="flex gap-5">
                        <h1 class="capitalize sec-title text-lg capitalize md:text-xl font-bold text-yellowColor">{{object.business_name}} Products</h1>
                    </div>
                    <a class="justify-self-end text-base text-slate-500 hover:text-slate-700" href="{% url 'supplier:products' %}?supplier={{object.business_name}}">View All</a>
                </div>
                <div class="section-body grid gap-2 md:gap-6 grid-cols-2 md:grid-cols-6 py-4"
                data-context="{{products.context_name}}">
                    {% for product in products.results %}
                        <div class="single-image-product-card overflow-hidden rounded grid gap-0.5 card-outlined">
                            <a class="grid gap-2 rounded overflow-hidden" href="{% url 'supplier:product-detail' product.product.slug %}">
                                <img loading="lazy" src="/media/{{product.images.image}}" alt="{{product.name}}"
                                    class="item-img rounded" style="width: 100%;object-fit:cover;">
                                <div class="item-details grid gap-0 py-1 md:py-2 px-4 gap-2"
                                    style="border-bottom: 1px solid hsla(213, 28%, 19%, .1);border-top: 1px solid hsla(213, 28%, 19%, .1)">
                                    <h5 class="text-sm font-bold leading-5 text-lightBackgroundColor">
                                        {{product.product.name|slice:":40"}}..
                                    </h5>
                                    <p class="text-xs font-medium">
                                        <span>{{product.product.currency}}</span>
                                        <span>{{product.product.price}}</span>
                                    </p>
                                </div>
                                <span class="grid items-center pb-2 px-4 font-semibold text-sm">By {{ product.supplier.profile.business_name }}</span>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    {% endif %}

    {% if stores.results %}
        <section class="main w-12/12 py-3 my-3">
            <div class=" w-full md:w-full mx-auto grid">                    
                <div class="flex p-2 px-2 pt-0 justify-between items-baseline">
                    <div class="flex gap-5">
                        <h1 class="capitalize sec-title text-lg capitalize md:text-xl font-bold text-yellowColor">{{object.business_name}} {% trans "Stores" %}</h1>
                    </div>
                    <a class="justify-self-end text-base text-slate-500 hover:text-slate-700" href="{% url 'supplier:store-list' %}">View All</a>
                </div>
                <div class="grid gap-3 md:grid-cols-5 rounded-md py-3" data-content="{{stores.context_name}}">
                    {% for store in stores.results %}
                        <div class="store-card grid items-start rounded-md card gap-4">
                            <a class="grid gap-1 rounded-md overflow-hidden" href="{% url 'supplier:store-detail' store.slug %}">
                                <img loading="lazy" src="/media/{{store.image}}" alt="{{store.name}}" class="img-wrapper rounded-md">
                                <div class="card-details grid items-end px-4 py-4">
                                    <h2 class="text-lg leading-5 text-white font-bold">    
                                        {{store.name}}
                                    </h2>
                                    <p class="text-slate-200 font-medium flex gap-2 flex-wrap">
                                        <span>{{store.supplier.profile.business_name}}</span>
                                        <!-- <span>120 Products</span> -->
                                    </p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    {% endif %}
 
{% endblock %}