B2B-Ecommerce-Platform/api/urls.py
from django.urls import path

app_name = "api"

from api import views

urlpatterns = [
    path("stores/", views.StoresListView.as_view(), name="stores"),
    path(
        "supplier/contracts/",
        views.SupplierContractsListView.as_view(),
        name="supplier/contracts",
    ),
    path("services/", views.ServicesListView.as_view(), name="services"),
    path("contracts/", views.ContractsListView.as_view(), name="contracts"),


    #---------------------------------------- Products ----------------------------------------
    path("products/", views.ProductsListView.as_view(), name="products"),
    path("supplier/products/", views.SupplierProductsListView.as_view(), name="supplier-products"),
    path("supplier/products/create/", views.ProductCreateApiView.as_view(), name="supplier-product-create"),
    path("supplier/products/<str:slug>/create/<str:data_type>/", views.ProductAppendDetailsApiView.as_view(), name="supplier-product-append-details"),
    path(
        "loading_products/",
        views.LoadingProductsListView.as_view(),
        name="loading_products",
    ),
    #---------------------------------------- Products ----------------------------------------

    #---------------------------------------- Calender ----------------------------------------
    path("events/", views.CalenderEventListView.as_view(), name="events"),
    path("events/create/", views.CalenderEventCreateView.as_view(), name="event-create"),
    path("events/<int:pk>/details/", views.CalenderEventDetailView.as_view(), name="event-detail"),
    path("events/<int:pk>/delete/", views.CalenderEventDeleteView.as_view(), name="event-detail"),
    #---------------------------------------- Calender ----------------------------------------


    #---------------------------------------- Cart ----------------------------------------
    path("cart/", views.CartListView.as_view(), name="cart"),
    path("cart/product/<str:product_slug>/add/", views.CartAppeendAppendView.as_view(), name="cart-add-product"),
    path("cart/product/<str:product_slug>/delete/", views.CartDeleteProductView.as_view(), name="cart-delete-product"),
    #---------------------------------------- Cart ----------------------------------------

    #---------------------------------------- Notifications ----------------------------------------
    path("notifications/", views.NotificationListView.as_view(), name="notification-list"),
    path("notifications/business/", views.NotificationBusinessListView.as_view(), name="Notification-business-list"),
    path("notifications/<str:category>/", views.NotificationCategoryListView.as_view(), name="Notification-category-list"),
    path("notifications/<int:pk>/delete/", views.NotificationDeleteView.as_view(), name="Notification-delete"),
    # path("notifications/<int:pk>/update/", views.NotificationUpdateView.as_view(), name="Notification-update"),
    #---------------------------------------- Notifications ----------------------------------------


    #---------------------------------------- chat ----------------------------------------
    path("user/<int:pk>/", views.UserInfoView.as_view(), name="user-info-retrieve"),
    path("business/<int:pk>/", views.BusinessInfoView.as_view(), name="business-info-retrieve"),
    path("chats/", views.ChatListView.as_view(), name="chat-list"),
    #---------------------------------------- chat ----------------------------------------

    path("chats/group/create/", views.CreateGroupChat.as_view(), name="create-group"),

]

B2B-Ecommerce-Platform/auth_app/urls.py
from django.urls import path

app_name = "auth_app"

from auth_app import views

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    # path('signup-buyer', views.SignUpView.as_view(), name='signup-buyer'),
    path(
        "activate/<uidb64>/<token>/", views.VerficationView.as_view(), name="activate"
    ),
    path("signup/business/", views.BusinessProfileView.as_view(), name="business"),
    path("logout", views.LogoutView, name="logout"),
]

B2B-Ecommerce-Platform/core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext as _

from manager import views
from payment.views import InitSubscriptionView

from django.core.signals import request_finished
from django.dispatch import receiver


# @receiver(request_finished)
# def my_callback(sender, **kwargs):
#     print("Request finished!")


# @receiver(request_finished)
# def requestTracker(request, **kwargs):
#     print(kwargs)
#     # if request.user_agent.is_mobile:
#     #     user_device = "mobile"
#     # elif request.user_agent.is_tablet:
#     #     user_device = "tablet"
#     # elif request.user_agent.is_bot:
#     #     user_device = "bot"
#     # else:
#     #     user_device = "pc"


#     print("*"*50)
#     print("Request finished!")
#     print("*"*50)
#     pass


# @receiver(got_request_exception)
# def get_exception_response(request, resolver, status_code, exception, sender=None):
# try:
#     callback, param_dict = resolver.resolve_error_handler(status_code)
#     response = callback(request, **dict(param_dict, exception=exception))
# except Exception:
#     signals.got_request_exception.send(sender=sender, request=request)
#     response = handle_uncaught_exception(request, resolver, sys.exc_info())

# return response
# pass


urlpatterns = i18n_patterns(
    path("", include("manager.urls", namespace="manager")),
    path(_("suppliers/"), include("supplier.urls", namespace="supplier")),
    path(_("buyer/"), include("buyer.urls", namespace="buyer")),
    path(_("auth/"), include("auth_app.urls", namespace="auth")),
    path(_("payments/"), include("payment.urls", namespace="payments")),
    path(_("support/admin/"), include("app_admin.urls", namespace="app_admin")),
    path(_("api/"), include("api.urls", namespace="api")),
    path(_("admin-api/"), include("admin_api.urls", namespace="admin-api")),
    path(_("communications/"), include("coms.urls", namespace="coms")),
    path(_("admin/"), admin.site.urls),
)
urlpatterns += [
    path("accounts/inactive/", InitSubscriptionView.as_view()),
    path("accounts/profile/", views.HomeView.as_view()),
    path("accounts/", include("allauth.urls")),
]

if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += [re_path(r"^rosetta/", include("rosetta.urls"))]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

B2B-Ecommerce-Platform/manager/urls.py
from django.urls import path

# apps
from manager import views

app_name = "manager"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    # showrooms
    path("showrooms/", views.ShowRoomListView.as_view(), name="showrooms"),
    path(
        "showroom/<str:slug>",
        views.ShowRoomDetailView.as_view(),
        name="showroom-detail",
    ),
    # services
    path("services/", views.ServiceListView.as_view(), name="services"),
    path("about/", views.AboutUsView.as_view(), name="about-us"),
    path("profile/", views.profile, name="profile"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("support/", views.SupportView.as_view(), name="support"),
    path("support/chatroom/", views.SupportChatroomView.as_view(), name="chatroom"),
    path(
        "support/discussion/<str:slug>/",
        views.SupportDiscussionView.as_view(),
        name="discussion",
    ),
    path(
        "support/discussions/",
        views.SupportDiscussionListView.as_view(),
        name="discussions",
    ),
    path(
        "support/create-discussion/",
        views.SupportCreateDiscussionView.as_view(),
        name="create-discussion",
    ),
    path("blocked", views.blockDasboardAccess, name="dashboard-blocked"),
    path("profile404", views.ProfileNotFound, name="profile-notfound"),
    # guides
    path("guides/memberships", views.memberships, name="guides-memberships"),
    path("guides/showrooms", views.showrooms, name="guides-showrooms"),
    path("guides/stores", views.stores, name="guides-stores"),
    path("guides/services", views.services, name="guides-services"),
    path("guides/products", views.products, name="guides-products"),
    path("guides/accounts", views.accounts, name="guides-accounts"),
]

B2B-Ecommerce-Platform/supplier/urls.py
from django.urls import path

# apps
from supplier import views

app_name = "supplier"

urlpatterns = [
    # supplier
    path(
        "supplier/<str:slug>",
        views.SupplierDetailView.as_view(),
        name="supplier-detail",
    ),
    path(
        "supplier/<str:slug>/contact/",
        views.SupplierContactView.as_view(),
        name="supplier-contact",
    ),
    path(
        "supplier/contract/<str:slug>/",
        views.SupplierContractView.as_view(),
        name="supplier-contract",
    ),
    # products
    path("products/", views.ProductListView.as_view(), name="products"),
    path(
        "products/<str:slug>", views.ProductDetailView.as_view(), name="product-detail"
    ),
    path("new-arivals/", views.NewArrivalView.as_view(), name="new-arivals"),
    path("superdeals/", views.SuperDealsView.as_view(), name="superdeals"),
    # categories
    path("categories/", views.CategoryListView.as_view(), name="category-list"),
    path(
        "category/<str:slug>",
        views.CategoryDetailView.as_view(),
        name="category-detail",
    ),
    # subcategory
    path(
        "category/<str:category_slug>/subcategory/<str:sub_category_slug>",
        views.SubCategoryDetailView.as_view(),
        name="subcategory-detail",
    ),
    # store
    path(
        "store/<str:slug>",
        views.StoreDetailView.as_view(),
        name="store-detail",
    ),
    path(
        "stores",
        views.StoreListView.as_view(),
        name="store-list",
    ),
    # path("stores/", views.CategoryListView.as_view(), name="store-list"),
    # path(
    #     "category/<str:slug>",
    #     views.CategoryDetailView.as_view(),
    #     name="category-detail",
    # ),
    path(
        "search",
        views.SearchView.as_view(),
        name="search",
    ),
    # dashboard
    path("dashboard", views.DashboardView.as_view(), name="dashboard"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("business/profile/", views.BusinessProfileView.as_view(), name="business_profile"),
    path("password-reset", views.password_reset, name="password-reset"),
    path(
        "editaccountsprofile/",
        views.EditAccountsProfileView.as_view(),
        name="dashboard-editaccountsprofile",
    ),
    path(
        "editbusinessprofile/<str:slug>/",
        views.EditBusinessProfileView.as_view(),
        name="dashboard-editbusinessprofile",
    ),
    path(
        "dashboard/products",
        views.DashboardProductsView.as_view(),
        name="dashboard-products",
    ),
    path(
        "dashboard/productscreate",
        views.DashboardProductsCreateView.as_view(),
        name="dashboard-productscreate",
    ),
    path(
        "dashboard/product/<str:slug>/edit/",
        views.DashboardProductEditView.as_view(),
        name="dashboard-productedit",
    ),
    path(
        "dashboard/product/customize/<str:slug>/",
        views.DashboardProductCustomizationView.as_view(),
        name="dashboard-productscustomize",
    ),
    path(
        "dashboard/bulkupload",
        views.DashboardBulkUploadView.as_view(),
        name="dashboard-bulkupload",
    ),
    path(
        "dashboard/product/<str:slug>/delete/",
        views.DashboardProductDeleteView.as_view(),
        name="dashboard-productdelete",
    ),
    path("dashboard/product/<str:product_slug>/store/<str:slug>/delete/", views.DashboardProductStoreDeleteView.as_view(), name="dashboard-storedelete"),
    path("dashboard/product/<str:product_slug>/category/<str:slug>/delete/", views.DashboardProductCategoryDeleteView.as_view(), name="dashboard-categorydelete"),
    path("dashboard/product/<str:product_slug>/sub_category/<str:slug>/delete/", views.DashboardProductSubCategoryDeleteView.as_view(), name="dashboard-sub_categorydelete"),
    path("dashboard/product/<str:product_slug>/pricing/<int:pk>/delete/", views.DashboardProductPricingDeleteView.as_view(), name="dashboard-pricingdelete"),
    path("dashboard/product/<str:product_slug>/tag/<int:pk>/delete/", views.DashboardProductTagDeleteView.as_view(), name="dashboard-tagdelete"),
    path("dashboard/product/<str:product_slug>/color/<int:pk>/delete/", views.DashboardProductColorDeleteView.as_view(), name="dashboard-colordelete"),
    path("dashboard/product/<str:product_slug>/material/<int:pk>/delete/", views.DashboardProductMaterialDeleteView.as_view(), name="dashboard-materialdelete"),
    path("dashboard/product/<str:product_slug>/image/<str:slug>/delete/", views.DashboardProductImageDeleteView.as_view(), name="dashboard-imagedelete"),
    path("dashboard/product/<str:product_slug>/video/<str:slug>/delete/", views.DashboardProductVideoDeleteView.as_view(), name="dashboard-videodelete"),


    path(
        "dashboard/stores/",
        views.DashboardStoresView.as_view(),
        name="dashboard-stores",
    ),
    path(
        "dashboard/stores/<str:slug>/assign-showroom/",
        views.assign_showroom,
        name="dashboard-assign-showroom",
    ),
    path(
        "dashboard/stores/<str:slug>/add-product/",
        views.add_product,
        name="dashboard-add-product",
    ),
    path(
        "dashboard/storescreate",
        views.DashboardStoresCreateView.as_view(),
        name="dashboard-storescreate",
    ),
    path(
        "dashboard/contracts",
        views.DashboardContractsView.as_view(),
        name="dashboard-contracts",
    ),
    path(
        "dashboard/contractsdetails/<int:pk>",
        views.DashboardContractsDetailsView.as_view(),
        name="dashboard-contractsdetails",
    ),
    path(
        "dashboard/contract/reject/<int:pk>",
        views.DashboardContractRejectDetailsView.as_view(),
        name="dashboard-contract-reject",
    ),
    path(
        "dashboard/contract/accept/<int:pk>",
        views.DashboardContractAcceptDetailsView.as_view(),
        name="dashboard-contract-accept",
    ),
    path(
        "dashboard/messenger",
        views.DashboardMessengerView.as_view(),
        name="dashboard-messenger",
    ),
    path(
        "dashboard/notification",
        views.DashboardNotificationView.as_view(),
        name="dashboard-notification",
    ),
    path(
        "dashboard/calendar",
        views.DashboardCalendarView.as_view(),
        name="dashboard-calendar",
    ),
    path(
        "dashboard/services",
        views.DashboardServicesView.as_view(),
        name="dashboard-services",
    ),
    path(
        "dashboard/servicescreate",
        views.DashboardServicesCreateView.as_view(),
        name="dashboard-servicescreate",
    ),

    path(
        "dashboard/advertise",
        views.DashboardAdvertiseView.as_view(),
        name="dashboard-advertise",
    ),
    path(
        "dashboard/advertise/payment/<str:slug>",
        views.DashboardAdvertisePaymentView.as_view(),
        name="dashboard-advertise-payment",
    ),
    path(
        "dashboard/payments",
        views.DashboardPaymentsView.as_view(),
        name="dashboard-payments",
    ),
    path(
        "dashboard/payments/advert",
        views.DashboardAdvertsPaymentsView.as_view(),
        name="dashboard-advert-payments",
    ),

    # orders
    path(
        "dashboard/orders/",
        views.DashboardOrderList.as_view(),
        name="dashboard-order-list",
    ),
    path(
        "dashboard/orders/<str:order_id>",
        views.DashboardOrderDetail.as_view(),
        name="dashboard-order-details",
    ),
    path('dashboard/order-excel/<str:order_id>', views.download_excel, name='order_excel'),

]

B2B-Ecommerce-Platform/manager/forms.py
from django import forms

from manager import models as ManagerModels

class ServiceFormManager(forms.ModelForm):
    class Meta:
        model = ManagerModels.Service
        fields = ["name", "description"]

class ShowroomFormManager(forms.ModelForm):
    class Meta:
        model = ManagerModels.Showroom
        fields = ["name", "location", "image"]

B2B-Ecommerce-Platform/templates/manager/showroom_detail.html
{% extends '../utils/layout.html' %}
{% load static %}
{% load i18n %}
{% block content %}

    <section class="main w-12/12 mt-5">
        <div class="page-starter grid w-full mx-auto cf-1 gap-4 overflow-hidden">
            <div class="hidden md:grid side-bar gap-3 content-start product-categories w-12/12 ">
                <div class="grid p-0 side-menu card rounded-none rounded-t-md overflow-hidden">
                    <h2 class="text-xl font-bold px-5 py-3 text-lighterBackgroundColor" style="background-color: hsla(213, 28%, 90%, .8);">
                        {% trans "Product Categories" %}</h2>
                    <ul class="grid gap-0.5 px-5 py-2" data-context='{{ product_categories.context_name }}'>
                        
                        {% for category in categories_header %}  
                            <li
                                class="side-menu-item text-slate-800 hover:text-black transition-colors transition-200 ease-in" data-category-index="{{ forloop.counter }}">
                                <a class="flex items-center justify-start gap-2 py-2" href='{% url "supplier:category-detail" category.slug %}?showroom={{object.slug}}'>
                                    <img style="inline-size: 1.8rem;aspect-ratio: 1;object-fit: cover;" src="/media/{{ category.image }}" alt="{{ category.name }}">
                                    <span>{{ category.name }}</span>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <a class="side-menu-footer bg-yellowColor flex gap-1 px-6 items-center py-3 text-white rounded-b-md" href="{% url 'supplier:category-list' %}">
                    <i class="ti-menu"></i>
                    <span>{% trans "All Categories" %}</span>
                </a>
            </div>
            <div class="promotion-area w-12/12 md:grid gap-3">
                <div id="banner-1" class="promotion-banner">
                    <div class="upper">
                        <div id="banner" style="block-size:100%;">
                            <div class="coursel" style="block-size: 100%;inline-size: 100%;">
                                <div class="header">
                                  <div class="progress-bar"></div>
                                </div>
                                <div class="slider-container">
                                  <button class="handle left-handle">
                                    <div class="text">&#8249;</div>
                                  </button>
                                  <div class="slider">
                                    {% for banner in banners.results %}
                                        <div class="item"><img src="/media/{{banner.image}}" alt="Owl Image"></div>
                                    {% endfor %}
                                  </div>
                                  <button class="handle right-handle">
                                    <div class="text">&#8250;</div>
                                  </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="lower" style="gap: .5rem;">
                        <div class="product-promotion-content" style="display:grid; align-content: center;gap: .25rem">
                            <h2 class="head text-xl font-bold text-white">{% trans "Top" %} {{ view_name }} {% trans "Suppliers" %}</h2>
                            <p class="desc text-normal text-slate-100" style="line-height: 20px;">{% trans "Get quality products from our top suppliers!" %}</p>
                        </div>
                        <div class="products">
                            {% for advert in adverts.results %}
                            <a href="{% url 'supplier:product-detail' advert.product.slug %}" class="product-card">
                                <div class="img-wrapper">
                                    <img src="/media/{{advert.main_image.image}}" alt="{{ advert.product.name }}">
                                </div>
                                <div class="content">
                                    <div class="content-group">
                                        <span class="symbol"></span>
                                        <span class="label">{{ advert.supplier.profile.business_name }}</span>
                                    </div>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="hidden md:grid gap-2 content-start">
                {% if text_promotion.results %}
                {% for text_promotion in text_promotion.results %}
                <a 
                    href="{% if text_promotion.type == 'SUPPLIERS' %} {% url 'auth_app:signup' %}?Supplier=1 {% elif text_promotion.type == 'BUYERS' %} {% url 'auth_app:signup' %}?Buyer=1 {% elif text_promotion.type == 'SHOWROOWS' %} {% url 'manager:showrooms' %} {% elif text_promotion.type == 'PRODUCTS' %} {% url 'supplier:products' %} {% endif %}" 
                    class="grid gap-2 items-start p-4 rounded-md" style="background-image: linear-gradient(to right top,hsl(350, 100%, 95%),hsl(350, 100%, 90%),hsl(350, 100%, 91%),hsl(350, 100%, 93%),hsl(350, 100%, 95%));">
                    <div class="grid">
                        <h4 class="font-semibold text-lighterBackgroundColor">{{text_promotion.name}}</h4>
                        <p class="text-lighterBackgroundColor text-base">{{text_promotion.description}}</p>
                    </div>
                    <button class="bg-black py-2 px-4 text-base justify-self-end rounded-full text-white font-semibold">{% trans "View More" %}</button>
                </a>
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </section>

    {% include '../utils/new_arrivals.html' with showroom=object.slug %}
    
    {% include '../utils/product_list.html' with with_title=False %}

    {% if stores.results %}
    <section class="main w-12/12 py-3">
        <div class="grid w-11/12 md:w-full mx-auto cf-1 gap-2">
            <div class="section-heading flex justify-start items-baseline gap-2">
                <h2 class="sec-title text-lg capitalize md:text-xl font-bold text-lightBackgroundColor">{{ object.name }} {% trans 'Stores' %}</h2>
            </div>
            <div class="grid gap-3 horizontal-scroll rounded-md py-3" data-context="{{ stores.context_name }}">
                {% for store in stores.results %}
                    <div class="store-card grid items-start rounded-md card gap-4">
                        <a class="grid gap-1 rounded-md overflow-hidden" href="{% url 'supplier:store-detail' store.slug %}">
                            <img loading="lazy" src="/media/{{store.image}}" alt="{{store.name}}" class="img-wrapper rounded-md">
                            <div class="card-details grid items-end px-4 py-4">
                                <h2 class="text-lg leading-5 text-white font-bold">    
                                    {{store.name}}
                                </h2>
                                <p class="text-slate-200 font-medium flex gap-2 flex-wrap">
                                    <span>{{store.supplier}}</span>
                                    <!-- <span>120 Products</span> -->
                                </p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endif %}

    {% include '../utils/category_group.html' %}

    <script>

        (function() {
          let slider = document.querySelector('.slider-container .slider');
          slider.style.setProperty("--items-per-screen",  1)
        })()
      
    </script>

{% endblock %}

B2B-Ecommerce-Platform/templates/manager/support.html
{% extends '../utils/layout.html' %}
{% load static %}
{% load i18n %}
{% load format_date %}
{% block content %}

<section class="main w-12/12 py-6 pt-0 gap-10" style="block-size: auto;">
    <div class="grid justify-center justify-center content-center justify-items-center content-center text-center gap-4 capitalize h-80 md:h-96" style="background-color: #0F172A;">
        <div class="grid gap-2 w-10/12">
            <h3 class="md:text-4xl text-2xl text-white font-bold">{% trans 'Support and Discussions' %}</h3>
            <p class="text-base text-slate-300 font-normal">{% trans 'Find help  and workarounds for the most common account-related issues.' %} </p>
        </div>

        <form action="{% url 'manager:discussions' %}" method="GET" class="flex bg-white rounded-full overflow-hidden w-10/12">
            <input type="text" style="width: 100%;padding: .7rem 2rem;font-size: 1rem;" name="search" placeholder="{% trans 'Search for help...' %}">
            <button type="submit" class="bg-yellowColor" style="border: none;padding: 1rem 2rem;">
                <i class="fa fa-search"></i>
            </button>
        </form>
        
        <div class="flex gap-2 my-4">
            <a href="{% url 'manager:chatroom' %}" class="bg-yellowColor text-white px-6 py-3 rounded-full">{% trans 'Send Message' %}</a>
            <a href="{% url 'manager:create-discussion' %}" class="bg-yellowColor text-white px-6 py-3 rounded-full">{% trans 'Create Discussion' %}</a>
        </div>
    </div>

    <div class="grid gap-4 md:gap-10 grid-cols-2 md:grid-cols-3 w-10/12 mx-auto py-8 justify-center">
        <a href="{% url 'manager:guides-accounts' %}" class="grid px-5 py-5 bg-slate-200 rounded-md card justify-center content-start justify-items-center gap-2">
            <i class="fa fa-user text-6xl md:text-8xl text-lghterBackgroundColor"></i>
            <div class="grid gap-1 justify-center text-center">
                <h2 class="font-bold md:text-lg text-xl">{% trans 'Accounts' %}</h2>
                <p class="text-slate-500">{% trans 'Get help on account related issues.' %}</p>
            </div>
        </a>
        <a href="" class="grid px-5 py-5 bg-slate-200 rounded-md card justify-center content-start justify-items-center gap-2">
            <i class="fa fa-credit-card  text-6xl md:text-8xl text-lghterBackgroundColor"></i>
            <div class="grid gap-1 justify-center text-center">
                <h2 class="font-bold md:text-lg text-xl">{% trans 'Payments' %}</h2>
                <p class="text-slate-500">{% trans 'Get help on payment related issues.' %}</p>
            </div>
        </a>
        <a href="{% url 'manager:guides-stores' %}" class="grid px-6 py-5 bg-slate-200 rounded-md card justify-center content-start justify-items-center gap-2">
            <i class="fa fa-home  text-6xl md:text-8xl text-lghterBackgroundColor"></i>
            <div class="grid gap-1 justify-center text-center">
                <h2 class="font-bold md:text-lg text-xl">{% trans 'Stores' %}</h2>
                <p class="text-slate-500">{% trans 'Help on Stores related issues.' %}</p>
            </div>
        </a>
        <a href="{% url 'manager:guides-showrooms' %}" class="grid px-5 py-5 bg-slate-200 rounded-md card justify-center content-start justify-items-center gap-2">
            <i class="fa fa-shopping-cart  text-6xl md:text-8xl text-lghterBackgroundColor"></i>
            <div class="grid gap-1 justify-center text-center">
                <h2 class="font-bold md:text-lg text-xl">{% trans 'Showrooms' %}</h2>
                <p class="text-slate-500">{% trans 'Get help on showroom related issues.' %}</p>
            </div>
        </a>
        <a href="{% url 'manager:guides-memberships' %}" class="grid px-5 py-5 bg-slate-200 rounded-md card justify-center content-start justify-items-center gap-2">
            <i class="fa fa-money  text-6xl md:text-8xl text-lghterBackgroundColor"></i>
            <div class="grid gap-1 justify-center text-center">
                <h2 class="font-bold md:text-lg text-xl">{% trans 'Memberships' %}</h2>
                <p class="text-slate-500">{% trans 'Get help on membership related issues.' %}</p>
            </div>
        </a>
        <a href="{% url 'manager:guides-products' %}" class="grid px-5 py-5 bg-slate-200 rounded-md card justify-center content-start justify-items-center gap-2">
            <i class="fa fa-product-hunt  text-6xl md:text-8xl text-lghterBackgroundColor"></i>
            <div class="grid gap-1 justify-center text-center">
                <h2 class="font-bold md:text-lg text-xl">{% trans 'Products' %}</h2>
                <p class="text-slate-500">{% trans 'Get help on product related issues.' %}</p>
            </div>
        </a>
    </div>

    {% if discussions %}
        <div class="grid gap-2 w-10/12 mx-auto my-4">
            <h3 class="text-2xl font-bold">{% trans 'Discussions' %}</h3>
            <div class="grid gap-4">
                {% for discussion in discussions %}
                    <a href="{% url 'manager:discussion' discussion.slug %}" class="grid gap-2 border border-solid border-slate-300 px-4 py-3 rounded">
                        <span class="flex gap-1 items-center">
                            <h4 class="font-semibold text-lg">{{discussion.subject}}</h4>
                            <span>-</span>
                            <span class="font-semibold text-base text-slate-500">{{ discussion.user.first_name }} {{ discussion.user.last_name }}</span>
                        </span>
                        <div class="grid gap-2">
                            <p class="text-base text-slate-600">{{ discussion.description }}</p>
                            <span class="text-sm text-slate-500">{{ discussion.created_on|format_date }}</span>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    {% endif %}
</section>

{% endblock %}